data:
  min_support: 0.01
  min_confidence: 0.5
  max_transactions: 1000
  min_items_per_transaction: 1
  max_items_per_transaction: 5

visualization:
  figure_size: [12, 8]
  style: 'seaborn'
  dpi: 300
  output_dir: 'reports/figures'

reporting:
  output_dir: 'reports'
  excel_filename: 'market_basket_analysis.xlsx'

# requirements.txt
pandas==2.0.0
numpy==1.24.0
mlxtend==0.22.0
seaborn==0.12.0
matplotlib==3.7.0
PyYAML==6.0
pytest==7.3.1
jupyter==1.0.0
